### PR TITLE
Add check when network list is empty to avoid exception

### PR DESCRIPTION
**Pull request by DanElias**
Issue: https://github.com/GoogleCloudDataproc/dataproc-jupyter-plugin/issues/152

### CODE REVIEW

**Review by ojarjur — APPROVED** [review]
Thank you so much for catching the issue and putting in the effort to fix it!

This looks great!

**Comment by ojarjur** [comment]
@DanElias thanks so much for the contribution!

We're going to perform our manual test validation on this and then update this thread once we've done that (ETA sometime tomorrow).

Assuming everything looks good we'll merge this right after that.

**Comment by DanElias** [comment]
Sounds good, thanks!

**Comment by harsha-accenture** [comment]
It looks good. We can go ahead and merge it.

**Pull request merged**
